spring:
  application:
    name: organiclever-be
  web:
    error:
      include-message: always
      include-binding-errors: always

server:
  port: 8202

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: never
