version: "2"

linters:
  default: standard
  enable:
    # Nil-safety linters
    - forcetypeassert # Forced type assertions that panic on wrong type
    - nilerr # Returns nil when err != nil check passed
    - nilnesserr # Returns different nil error after err != nil check
    - nilnil # Simultaneous return of nil error and invalid value
  settings:
    govet:
      enable:
        - nilness # Reports nil pointer dereferences and redundant nil checks
    staticcheck:
      checks:
        - all # enable all SA* (correctness), ST* (style), S* (simplify), QF* (quickfix)
        - -ST1013 # skip: HTTP status code constants (too strict for test code)
        - -ST1015 # skip: default case position in switch (purely cosmetic)
        - -ST1017 # skip: yoda conditions (rarely relevant in Go)
        - -ST1018 # skip: zero-width characters in strings (extremely niche)
