version: "2"

linters:
  default: standard
  enable:
    # Nil-safety linters
    - forcetypeassert # Forced type assertions that panic on wrong type
    - nilerr # Returns nil when err != nil check passed
    - nilnesserr # Returns different nil error after err != nil check
    - nilnil # Simultaneous return of nil error and invalid value
  settings:
    govet:
      enable:
        - nilness # Reports nil pointer dereferences and redundant nil checks
    staticcheck:
      checks:
        - ST1000 # Package comments
        - ST1003 # Naming conventions (e.g. API not Api, URL not Url)
